import numpy as np
n1 = np.arange(20)
print(n1)
print("data type of n1:",type(n1))  # [ndarray means = in dimentional array]
print("dimension of n1:",n1.ndim)
print("shape of n1:",n1.shape)
print("data type of each element:",n1.dtype)
print('########################')
n2=n1.reshape(4,5)
print(n2)
print("data type of n2:",type(n2))
print("dimension of n2:",n2.ndim)
print("shape of n2:",n2.shape)
print("data type of each element:",n2.dtype)

#####################################################

p1=np.arange(2,10)
print(p1)
p2=np.arange(1,20,3)
print(p2)
print('#########################')
p3=np.arange(1,2,.3)
print(p3)
p4=np.arange(1,2,.03)
print(p4)
print("No. of elements= ",len(p4))
print('#######################')
m1=np.linspace(1,2,10)
print(m1)
print('#########################')
m2=np.linspace(1,2,100)
print(m2)
print('##########################')
m3=np.linspace(1,2,10000)
print(m3)
print('########matrix############')
m4=m3.reshape(100,100)
print(m4)